# Generated by Django 3.1.2 on 2020-10-07 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la categoría', max_length=200, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Código representativo de la categoría', max_length=20, verbose_name='Código')),
                ('description', models.TextField(blank=True, help_text='Descripción categoría', null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoría',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Codigo control inventario', max_length=50, unique=True, verbose_name='SKU')),
                ('name', models.CharField(help_text='Nombre producto', max_length=150, verbose_name='Nombre')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio de venta en USD.', max_digits=8, verbose_name='Precio venta')),
                ('stock', models.BooleanField(default=True, help_text='Existencia del producto', verbose_name='Disponibilidad')),
                ('description', models.TextField(blank=True, default='', help_text='Descripción del producto', verbose_name='Descripción')),
                ('category', models.ForeignKey(blank=True, help_text='Categoría del producto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
    ]
