# Generated by Django 3.1.2 on 2020-10-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=True, help_text='Muestra categorias activas', verbose_name='Estado'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='categoria',
        ),
    ]
