# Generated by Django 3.1.2 on 2020-10-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201015_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Texto amigable a mostrar en la url.', max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Texto amigable a mostrar en la url.', max_length=200, null=True),
        ),
    ]
