# Generated by Django 3.1.2 on 2020-10-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único de la orden', max_length=100, unique=True, verbose_name='Código')),
                ('date_created', models.DateTimeField(auto_now=True, help_text='Fecha de emisión', verbose_name='Fecha')),
                ('billing_name', models.CharField(help_text='Nombres que se ingresan para la factura', max_length=200, verbose_name='Nombres factura')),
                ('billing_dni', models.CharField(help_text='Numero de idenitifacion', max_length=20, verbose_name='No. Identificación')),
                ('billing_email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('billing_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_name', models.CharField(help_text='Nombres que reciben el pedido de la orden', max_length=200, verbose_name='Nombres para entrega')),
                ('shipping_address', models.CharField(max_length=200, verbose_name='Dirección de entrega')),
                ('shipping_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono para la entrega')),
                ('payment_mode', models.IntegerField(choices=[(1, 'Efectivo'), (2, 'Depostio/Transferencia'), (3, 'Tarejeta de crédito')], default=1, help_text='modo de pago, Ej tarjeta de credito', verbose_name='Forma de pago')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='SubTotal')),
                ('base12', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Base 12%')),
                ('base0', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Base 0%')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='IVA')),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Fee entrega')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Total')),
                ('tracking_status', models.IntegerField(choices=[(1, 'Creada'), (2, 'Procesada'), (3, 'Enviada'), (4, 'Pagada'), (5, 'Completada'), (6, 'Cancelada')], default=1, help_text='Estado de seguimiento de la orden', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'db_table': 'orden',
            },
        ),
    ]
