# Generated by Django 3.1.2 on 2020-10-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='base0',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Base 0%'),
        ),
        migrations.AlterField(
            model_name='order',
            name='base12',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Base 12%'),
        ),
        migrations.AlterField(
            model_name='order',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='SubTotal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Total'),
        ),
    ]
