# Generated by Django 3.1.2 on 2020-10-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20201027_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor del descuento'),
        ),
    ]
